#!/bin/bash

# Startup script for PLY Scanner Backend

echo "======================================"
echo "PLY Scanner Backend - Startup Script"
echo "======================================"
echo ""

# Get script directory
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$SCRIPT_DIR"

# Check if virtual environment exists
if [ ! -d "venv310" ]; then
    echo "❌ Virtual environment not found!"
    echo "Please create it first:"
    echo "  python3.10 -m venv venv310"
    echo "  source venv310/bin/activate"
    echo "  pip install -r requirements.txt"
    exit 1
fi

# Activate virtual environment
echo "Activating virtual environment..."
source venv310/bin/activate

# Get local IP address
echo ""
echo "Finding local IP address..."
LOCAL_IP=$(ifconfig | grep "inet " | grep -v 127.0.0.1 | awk '{print $2}' | head -n 1)
# Clean hostname: remove spaces, apostrophes, special chars
HOSTNAME=$(scutil --get ComputerName | sed 's/ /-/g' | sed "s/'//g" | sed 's/[^a-zA-Z0-9-]//g')

if [ -z "$LOCAL_IP" ]; then
    LOCAL_IP="localhost"
    echo "⚠️  Could not determine local IP address"
else
    echo "✅ Local IP: $LOCAL_IP"
fi

echo "✅ Local hostname: ${HOSTNAME}.local"

# Generate auto-config file for Expo app
echo "📝 Generating auto-config for Expo app..."
cat > ply-processor/constants/server-auto.ts << EOF
/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by start_backend.sh on $(date)
 */

export const AUTO_DISCOVERED_SERVER = {
  hostname: 'http://${HOSTNAME}.local:8000',
  ip: 'http://${LOCAL_IP}:8000',
  timestamp: '$(date -u +"%Y-%m-%dT%H:%M:%SZ")',
};
EOF

echo "✅ Config generated at ply-processor/constants/server-auto.ts"

echo ""
echo "======================================"
echo "IMPORTANT: App Configuration Updated!"
echo "======================================"
echo "Expo App will auto-connect to:"
echo "  Hostname: http://${HOSTNAME}.local:8000"
echo "  Direct IP: http://$LOCAL_IP:8000"
echo ""
echo "For iOS Native App (iOS_App/PLYScanner/NetworkService.swift):"
echo "  Set baseURL to: http://$LOCAL_IP:8000"
echo ""
echo "💡 Expo app config is automatically updated!"
echo ""
echo "======================================"
echo ""

# Check if port 8000 is already in use
if lsof -Pi :8000 -sTCP:LISTEN -t >/dev/null ; then
    echo "⚠️  Port 8000 is already in use!"
    echo "Kill existing process? (y/n)"
    read -r response
    if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]; then
        kill -9 $(lsof -t -i:8000)
        echo "✅ Killed process on port 8000"
        sleep 1
    else
        echo "❌ Cannot start server while port is in use"
        exit 1
    fi
fi

# Start the FastAPI server
echo "Starting FastAPI server..."
echo "API will be available at:"
echo "  Local:    http://localhost:8000"
echo "  Network:  http://$LOCAL_IP:8000"
echo "  Hostname: http://${HOSTNAME}.local:8000 (recommended)"
echo ""
echo "API Documentation:"
echo "  http://localhost:8000/docs"
echo ""
echo "Press Ctrl+C to stop the server"
echo ""
echo "======================================"
echo ""

python -m uvicorn src.api.ply_upload:app --host 0.0.0.0 --port 8000 --reload
